name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      options: --user root

    steps:
      - name: Install system dependencies
        run: |
          apk update
          apk add --no-cache \
            build-base \
            openssl-dev \
            openssl-libs-static \
            opus-dev \
            pkgconfig \
            cmake \
            clang \
            nasm \
            git \
            curl

      - name: Install Rustup
        run: |
          # Instal Rustup resmi
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          # Tambahkan cargo ke PATH sesi ini
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Target
        run: |
          # Gunakan full path karena PATH mungkin belum ter-refresh di langkah yang sama
          $HOME/.cargo/bin/rustup target add x86_64-unknown-linux-musl

      - name: Checkout KORD
        uses: actions/checkout@v4
        with:
          repository: KeyouXZ/KORD
          token: ${{ secrets.GH_TOKEN }}
          path: KORD

      - name: Build
        working-directory: KORD
        env:
          OPENSSL_STATIC: 1
          # Linker musl butuh bantuan untuk menemukan library statik
          LIBRARY_PATH: /usr/lib
        run: |
          $HOME/.cargo/bin/cargo build --profile max --target x86_64-unknown-linux-musl

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: kord-linux-binary
          path: KORD/target/x86_64-unknown-linux-musl/max/kord
