name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            libssl-dev pkg-config cmake clang nasm golang-go

      - name: Install cargo-zigbuild + zig
        run: |
          cargo install cargo-zigbuild
          pip install ziglang

      - name: Checkout KORD
        uses: actions/checkout@v4
        with:
          repository: KeyouXZ/KORD
          token: ${{ secrets.GH_TOKEN }} # Ensure this secret is stored in your current repo's secrets
          path: KORD # This puts the code into a folder named KORD

      - name: Build
        working-directory: KORD
        env:
          OPENSSL_LIB_DIR: /usr/lib/x86_64-linux-gnu
          OPENSSL_INCLUDE_DIR: /usr/include/openssl
        run: |
          cargo zigbuild --profile max --target x86_64-unknown-linux-gnu.2.31

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: kord-linux-x86_64-glibc2.31
          path: KORD/target/x86_64-unknown-linux-gnu/max/kord
